# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-09 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180309_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='static/%Y/%m/%d'),
        ),
    ]
